name: fibermatcher
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - numpy=1.23.5
  - scipy=1.10.1
  - scikit-image=0.21.0
  - scikit-learn=1.3.2
  - matplotlib=3.7.5
  - pandas=2.0.3
  - tqdm=4.65.0
  - joblib=1.4.2
  - pyyaml=6.0.1
  - pillow=10.4.0
  - pip:
    - cellpose==2.2.2
    - czifile==2019.7.2
    - opencv-python-headless==4.8.0.74
    - imageio==2.35.1
    - umap-learn==0.5.7
